version: "3.8"

services:
  web:
    build: ./project
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./project:/usr/src/app
    env_file:
      - ./project/.env
    depends_on:
      - redis

  worker1:
    build: ./project
    command: celery -A main.celery worker --loglevel=info
    volumes:
      - ./project:/usr/src/app
    env_file:
      - ./project/.env
    depends_on:
      - web
      - redis

  worker2:
    build: ./project
    command:
      celery -A main.celery worker -Q periodic --loglevel=info -n periodic
    volumes:
      - ./project:/usr/src/app
    env_file:
      - ./project/.env
    depends_on:
      - web
      - redis

  beat:
    build: ./project
    command: celery -A main.celery beat
    volumes:
      - ./project:/usr/src/app
    env_file:
      - ./project/.env
    depends_on:
      - web
      - redis

  redis:
    image: redis:7

  dashboard:
    build: ./project
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5555:5555
    env_file:
      - ./project/.env
    depends_on:
      - web
      - redis
      - worker1
      - worker2
      - beat
