version: "3.8"

services:
  backend:
    build: ./project
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./project:/usr/src/app
    env_file:
      - ./project/.env
    depends_on:
      - queue

  worker1:
    build: ./project
    command: celery -A main.celery worker --loglevel=info
    volumes:
      - ./project:/usr/src/app
    env_file:
      - ./project/.env
    depends_on:
      - backend
      - queue

  worker2:
    build: ./project
    command:
      celery -A main.celery worker -Q periodic --loglevel=info -n periodic
    volumes:
      - ./project:/usr/src/app
    env_file:
      - ./project/.env
    depends_on:
      - backend
      - queue

  beat:
    build: ./project
    command: celery -A main.celery beat
    volumes:
      - ./project:/usr/src/app
    env_file:
      - ./project/.env
    depends_on:
      - backend
      - queue

  queue:
    # image: redis:7
    image: rabbitmq:3

  dashboard:
    # build: ./project
    # command: celery --broker=redis://redis:6379/0 flower --port=5555
    image: mher/flower:0.9.7
    command: "--broker=amqp://guest@queue:5672//"
    ports:
      - 5555:5555
    env_file:
      - ./project/.env
    depends_on:
      - backend
      - queue
      - worker1
      - worker2
      - beat
